/**
 * Component Card Store — src/store/componentCardStore.ts
 *
 * Phase CV2.3: Component Cards on Canvas
 *
 * Owns the state for all component cards displayed on the infinite canvas in
 * 'build' and 'govern' canvas view modes. Deliberately kept separate from
 * canvasStore, which owns single-file editing lifecycle state (activeFilePath,
 * saveState, mithrilViolations). The card system is orthogonal:
 *
 *   - cards[]           — All indexed components in the active project.
 *   - selectedCardId    — ID of the currently selected card (independent of
 *                         canvasStore.activeSelection, which is a data-flint-id
 *                         within a single file).
 *   - cardPositions     — Persisted spatial positions keyed by card ID.
 *   - isLoaded / isLoading — Fetch lifecycle flags.
 *
 * Cross-store coordination rule (Commandment anti-pattern):
 *   DO NOT import canvasStore here. When selectedCardId changes, a React effect
 *   in App.tsx reads the new ID, finds the card, and calls:
 *     canvasStore.setActiveFile(card.filePath)
 *     canvasStore.setRightTab('properties')
 *
 * Position persistence:
 *   updatePosition()  — Updates in-memory map immediately.
 *   savePositions()   — Debounced (500 ms). Calls window.flintAPI.components.savePositions().
 *   loadCards()       — Calls window.flintAPI.components.loadPositions() and merges
 *                       saved positions. Cards without saved positions get auto-layout
 *                       positions computed from the grid algorithm below.
 *
 * Auto-layout algorithm (first open, or no .flint/card-positions.json):
 *   1. Group by category: primitive → molecule → organism → page → layout → uncategorized.
 *   2. Within each group, sort alphabetically by name.
 *   3. Grid: 4 columns, 240px column width, 280px row height, 40px gap.
 *   4. Each category group starts on a new row with 60px vertical gap between groups.
 *
 * React Flow selectors:
 *   toFlowNodes() — Maps cards + positions to Node<ComponentCardNodeData>[].
 *   toFlowEdges() — Maps card.dependencies to Edge<DependencyEdgeData>[] for Govern mode.
 *
 * Commandment compliance:
 *   C3  — No Array.map in this store; IDs are stable hashes from the IPC layer.
 *   C12 — All mutations use set() with spread — never mutate objects in place.
 *   Process boundary — No fs/node: imports. All IPC through window.flintAPI.
 */

import { create } from 'zustand'
import type { Node, Edge } from '@xyflow/react'
import type { ComponentCardData, ComponentCategory } from '../types/flint-api'
import { useNotificationStore } from './notificationStore'

// ── Governance Stickers ────────────────────────────────────────────────────────

/**
 * The five predefined governance sticker types.
 * Placed on component cards in Govern mode to communicate workflow status
 * at a glance without opening the PropertiesPanel.
 */
export type GovernanceStickerType = 'needs-review' | 'approved' | 'deprecated' | 'wip' | 'blocked'

/**
 * A single governance sticker attached to a component card.
 * V1: in-memory only. Persistence via the annotation engine is a future phase.
 */
export interface GovernanceSticker {
    /** UUID — generated by addSticker. */
    id: string
    /** One of the five predefined sticker types. */
    type: GovernanceStickerType
    /** The component card this sticker is pinned to. */
    componentId: string
    /** Optional free-text note from the person who placed the sticker. */
    note?: string
    /** ISO 8601 timestamp of when the sticker was placed. */
    createdAt: string
}

/**
 * Visual configuration for each GovernanceStickerType.
 * colorClass uses only palette token classes — no arbitrary hex (Commandment 2).
 */
export const STICKER_CONFIG: Record<
    GovernanceStickerType,
    { label: string; icon: string; colorClass: string }
> = {
    'needs-review': {
        label: 'Needs Review',
        icon: 'Eye',
        colorClass: 'bg-amber-500/20 text-amber-400 border-amber-500/30',
    },
    approved: {
        label: 'Approved',
        icon: 'CheckCircle',
        colorClass: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
    },
    deprecated: {
        label: 'Deprecated',
        icon: 'Archive',
        colorClass: 'bg-red-500/20 text-red-400 border-red-500/30',
    },
    wip: {
        label: 'WIP',
        icon: 'Hammer',
        colorClass: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
    },
    blocked: {
        label: 'Blocked',
        icon: 'XOctagon',
        colorClass: 'bg-red-500/20 text-red-300 border-red-500/40',
    },
}

/** Stable ordering for rendering sticker pickers. */
export const STICKER_TYPES: GovernanceStickerType[] = [
    'needs-review',
    'approved',
    'deprecated',
    'wip',
    'blocked',
]

// ── Re-export for convenience ──────────────────────────────────────────────────

export type { ComponentCardData }

// ── Derived types for React Flow integration ───────────────────────────────────

/**
 * Data payload passed to the ComponentCardNode via React Flow's `data` prop.
 * Assembled in toFlowNodes() from componentCardStore state.
 */
export interface ComponentCardNodeData {
    card: ComponentCardData
    isSelected: boolean
    canvasView: 'build' | 'govern'
    [key: string]: unknown
}

/**
 * Data payload passed to the DependencyEdge via React Flow's `data` prop.
 * Assembled in toFlowEdges() from card.dependencies.
 */
export interface DependencyEdgeData {
    /** Health grade of the target (downstream) component. Null when health data not available. */
    targetGrade: NonNullable<ComponentCardData['health']>['grade'] | null
    [key: string]: unknown
}

// ── Auto-layout constants ──────────────────────────────────────────────────────

const GRID_COLUMN_WIDTH = 240
const GRID_ROW_HEIGHT = 280
const GRID_GAP = 40
const GRID_COLUMNS = 4
const CATEGORY_GROUP_GAP = 60

/** Ordered category groups for the auto-layout algorithm. */
const CATEGORY_ORDER: ComponentCardData['category'][] = [
    'primitive',
    'molecule',
    'organism',
    'page',
    'layout',
    'uncategorized',
]

// ── Store shape ────────────────────────────────────────────────────────────────

interface ComponentCardState {
    /** All component cards for the current project. Empty when no project is open. */
    cards: ComponentCardData[]
    /** ID of the currently selected card, or null. */
    selectedCardId: string | null
    /** Persisted spatial positions. Keyed by card ID. */
    cardPositions: Record<string, { x: number; y: number }>
    /** True when the initial card load has completed (success or error). */
    isLoaded: boolean
    /** True while the components:list IPC call is in flight. */
    isLoading: boolean
    /** Error message from the last failed loadCards() call, or null. */
    error: string | null
    /**
     * CV2.7: Search query for filtering the component card grid.
     * Empty string means no filter is active.
     */
    searchQuery: string
    /**
     * CV2.7: Category filter for the component card grid.
     * 'all' means no category filter is applied.
     */
    categoryFilter: ComponentCategory | 'all'
    /**
     * Coverage heat map overlay visibility in Govern mode.
     * When true, each component card shows a radial gradient halo
     * colored by health grade. Defaults to true.
     */
    showCoverageHeatMap: boolean
    /**
     * All in-memory governance stickers.
     * V1: lost on app restart. Persistence via the annotation engine is future work.
     */
    stickers: GovernanceSticker[]
}

interface ComponentCardActions {
    /**
     * Fetches the component list via `components:list` IPC and populates `cards`.
     * Also loads persisted positions via `components:load-positions`.
     * Cards without saved positions receive auto-computed grid positions.
     *
     * Called when `canvasView` transitions to 'build' or 'govern'.
     */
    loadCards: () => Promise<void>

    /**
     * Selects a card by ID. Pass null to deselect.
     * Cross-store coordination (setActiveFile, setRightTab) happens in App.tsx
     * via a useEffect that watches this value — NOT inside this action.
     */
    selectCard: (cardId: string | null) => void

    /**
     * Updates the position for a single card in the in-memory map.
     * Called on React Flow `onNodesChange` (drag end).
     * Does NOT write to disk — call savePositions() to persist.
     */
    updatePosition: (cardId: string, position: { x: number; y: number }) => void

    /**
     * Persists all current positions to disk via `components:save-positions` IPC.
     * Debounced at 500 ms — safe to call freely on every drag event.
     */
    savePositions: () => void

    /**
     * CV2.6: Overrides the category for a single card.
     *
     * Optimistically updates the card's category in local state so the UI
     * responds immediately. Then calls `window.flintAPI.components.setCategory`
     * to persist the override to `.flint/category-overrides.json`. On IPC
     * failure, the card is reverted to its previous category and a notification
     * is pushed to inform the user.
     *
     * Build mode only — the caller (ComponentCardNode) gates this to 'build'.
     */
    setCategoryOverride: (cardId: string, category: ComponentCategory) => void

    /**
     * CV2.7: Sets the search query for filtering the component card grid.
     * Pass an empty string to clear the search filter.
     */
    setSearchQuery: (query: string) => void

    /**
     * CV2.7: Sets the category filter for the component card grid.
     * Pass 'all' to show all categories.
     */
    setCategoryFilter: (category: ComponentCategory | 'all') => void

    /**
     * Toggles the coverage heat map overlay on/off in Govern mode.
     */
    toggleCoverageHeatMap: () => void

    /**
     * Clears all cards, positions, selection, load state, and search filters.
     * Called on project close (closeWorkspace) to prevent stale data bleeding
     * into the next project.
     */
    clearCards: () => void

    /**
     * Adds a new governance sticker to the given component card.
     * Generates a UUID and ISO timestamp internally.
     * Has no effect if the same type is already attached to the card
     * (one sticker of each type per card).
     */
    addSticker: (componentId: string, type: GovernanceStickerType, note?: string) => void

    /**
     * Removes the sticker with the given id.
     * No-ops gracefully if the id is not found.
     */
    removeSticker: (stickerId: string) => void

    /**
     * Returns all stickers currently attached to the given component card.
     * Pure selector — no mutations. Callers should memoize when rendering lists.
     */
    getStickersForCard: (componentId: string) => GovernanceSticker[]

    /**
     * Computes React Flow Node<ComponentCardNodeData>[] from cards + positions.
     * Pure selector — reads state, returns derived data, no mutations.
     *
     * @param canvasView - 'build' or 'govern'. Passed through to node data so
     *                     ComponentCardNode can render the appropriate UI without
     *                     subscribing to canvasStore directly.
     */
    toFlowNodes: (canvasView?: 'build' | 'govern') => Node<ComponentCardNodeData>[]

    /**
     * Computes React Flow Edge<DependencyEdgeData>[] from card.dependencies.
     * Pure selector. Only call in Govern mode (XYCanvas gates this).
     *
     * Edges are produced for each (sourceCard, targetCard) pair where
     * targetCard.importPath appears in sourceCard.dependencies[].
     */
    toFlowEdges: () => Edge<DependencyEdgeData>[]
}

type ComponentCardStore = ComponentCardState & ComponentCardActions

// ── Module-level debounce timer ────────────────────────────────────────────────
// Singleton store — one timer is sufficient. Mirrors the pattern in canvasStore.

let _saveTimer: ReturnType<typeof setTimeout> | null = null

// ── Auto-layout helper ─────────────────────────────────────────────────────────

/**
 * Computes grid positions for all cards, grouped by category.
 * Returns a map of cardId → { x, y }.
 *
 * Any card whose ID already exists in `existingPositions` is skipped —
 * only missing positions are computed. This means drag-persisted positions
 * are never clobbered by auto-layout on subsequent loadCards() calls.
 */
function computeAutoLayout(
    cards: ComponentCardData[],
    existingPositions: Record<string, { x: number; y: number }>
): Record<string, { x: number; y: number }> {
    const result: Record<string, { x: number; y: number }> = {}

    // Group cards by category, sorted alphabetically within each group.
    const grouped = new Map<ComponentCardData['category'], ComponentCardData[]>()
    for (const category of CATEGORY_ORDER) {
        grouped.set(category, [])
    }
    for (const card of cards) {
        if (!existingPositions[card.id]) {
            const group = grouped.get(card.category) ?? grouped.get('uncategorized')!
            group.push(card)
        }
    }
    for (const group of grouped.values()) {
        group.sort((a, b) => a.name.localeCompare(b.name))
    }

    let currentY = 0
    let isFirstGroup = true

    for (const category of CATEGORY_ORDER) {
        const group = grouped.get(category)
        if (!group || group.length === 0) continue

        // Add vertical gap between category groups (but not before the first one).
        if (!isFirstGroup) {
            currentY += CATEGORY_GROUP_GAP
        }
        isFirstGroup = false

        for (let i = 0; i < group.length; i++) {
            const col = i % GRID_COLUMNS
            const row = Math.floor(i / GRID_COLUMNS)
            const x = col * (GRID_COLUMN_WIDTH + GRID_GAP)
            const y = currentY + row * (GRID_ROW_HEIGHT + GRID_GAP)
            result[group[i].id] = { x, y }
        }

        // Advance currentY past all rows in this group.
        const rowCount = Math.ceil(group.length / GRID_COLUMNS)
        currentY += rowCount * (GRID_ROW_HEIGHT + GRID_GAP)
    }

    return result
}

// ── Store ──────────────────────────────────────────────────────────────────────

export const useComponentCardStore = create<ComponentCardStore>((set, get) => ({
    // ── Initial State ────────────────────────────────────────────────────────

    cards: [],
    selectedCardId: null,
    cardPositions: {},
    isLoaded: false,
    isLoading: false,
    error: null,
    searchQuery: '',
    categoryFilter: 'all',
    showCoverageHeatMap: true,
    stickers: [],

    // ── Actions ──────────────────────────────────────────────────────────────

    loadCards: async () => {
        set({ isLoading: true, error: null })

        try {
            // Parallel IPC: fetch card list and persisted positions simultaneously.
            const [cards, savedPositions] = await Promise.all([
                window.flintAPI.components.list(),
                window.flintAPI.components.loadPositions(),
            ])

            // Compute auto-layout only for cards that do not have saved positions.
            const autoPositions = computeAutoLayout(cards, savedPositions)

            // Merge: saved positions take precedence over auto-layout.
            const mergedPositions: Record<string, { x: number; y: number }> = {
                ...autoPositions,
                ...savedPositions,
            }

            set({
                cards,
                cardPositions: mergedPositions,
                isLoaded: true,
                isLoading: false,
                error: null,
            })
        } catch (err) {
            const message = err instanceof Error ? err.message : 'Failed to load components'
            console.error('[Flint] componentCardStore.loadCards failed:', err)
            set({
                isLoaded: true,
                isLoading: false,
                error: message,
            })
        }
    },

    selectCard: (cardId) => {
        set({ selectedCardId: cardId })
    },

    updatePosition: (cardId, position) => {
        // Commandment C12 (Atomic Queuing): spread to create a new object reference
        // so Zustand detects the change via shallow equality.
        set((state) => ({
            cardPositions: {
                ...state.cardPositions,
                [cardId]: position,
            },
        }))
    },

    savePositions: () => {
        // Cancel any pending timer.
        if (_saveTimer !== null) {
            clearTimeout(_saveTimer)
            _saveTimer = null
        }

        _saveTimer = setTimeout(() => {
            _saveTimer = null
            const { cardPositions } = get()
            window.flintAPI.components
                .savePositions(cardPositions)
                .catch((err: unknown) => {
                    console.error('[Flint] componentCardStore.savePositions IPC failed:', err)
                })
        }, 500)
    },

    setCategoryOverride: (cardId, category) => {
        const { cards } = get()

        // Find the card to capture its previous category for rollback.
        const targetIndex = cards.findIndex((c) => c.id === cardId)
        if (targetIndex === -1) {
            console.warn(`[Flint] setCategoryOverride: card ${cardId} not found in store`)
            return
        }
        const previousCategory = cards[targetIndex].category

        // Optimistic update: replace the card's category in local state.
        const updatedCards = cards.map((c) =>
            c.id === cardId ? { ...c, category } : c,
        )
        set({ cards: updatedCards })

        // Persist via IPC.
        window.flintAPI.components
            .setCategory({ componentId: cardId, category })
            .then(() => {
                // Success: push a brief confirmation notification.
                const cardName = updatedCards[targetIndex]?.name ?? cardId
                useNotificationStore.getState().push({
                    type: 'mutation',
                    title: 'Category updated',
                    message: `${cardName} reclassified as ${category}`,
                    severity: 'success',
                    autoDismissMs: 3000,
                })
            })
            .catch((err: unknown) => {
                // IPC failure: revert optimistic update.
                console.error('[Flint] setCategoryOverride IPC failed — reverting:', err)
                set((state) => ({
                    cards: state.cards.map((c) =>
                        c.id === cardId ? { ...c, category: previousCategory } : c,
                    ),
                }))
                useNotificationStore.getState().push({
                    type: 'error',
                    title: 'Category update failed',
                    message: 'Could not save category override. Change reverted.',
                    severity: 'error',
                    autoDismissMs: 5000,
                })
            })
    },

    toggleCoverageHeatMap: () => {
        set((state) => ({ showCoverageHeatMap: !state.showCoverageHeatMap }))
    },

    setSearchQuery: (query) => {
        set({ searchQuery: query })
    },

    setCategoryFilter: (category) => {
        set({ categoryFilter: category })
    },

    clearCards: () => {
        // Cancel any pending save before clearing so stale positions are not written.
        if (_saveTimer !== null) {
            clearTimeout(_saveTimer)
            _saveTimer = null
        }
        set({
            cards: [],
            selectedCardId: null,
            cardPositions: {},
            isLoaded: false,
            isLoading: false,
            error: null,
            searchQuery: '',
            categoryFilter: 'all',
            stickers: [],
        })
    },

    addSticker: (componentId, type, note) => {
        const { stickers } = get()
        // Enforce one sticker of each type per card (idempotent placement).
        const alreadyExists = stickers.some(
            (s) => s.componentId === componentId && s.type === type,
        )
        if (alreadyExists) return

        // UUID via crypto.randomUUID (available in Electron's Chromium renderer).
        const id =
            typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function'
                ? crypto.randomUUID()
                : `sticker-${Date.now()}-${Math.random().toString(36).slice(2)}`

        const sticker: GovernanceSticker = {
            id,
            type,
            componentId,
            note,
            createdAt: new Date().toISOString(),
        }
        set({ stickers: [...stickers, sticker] })
    },

    removeSticker: (stickerId) => {
        set((state) => ({
            stickers: state.stickers.filter((s) => s.id !== stickerId),
        }))
    },

    getStickersForCard: (componentId) => {
        return get().stickers.filter((s) => s.componentId === componentId)
    },

    toFlowNodes: (canvasView = 'build') => {
        const { cards, cardPositions, selectedCardId, searchQuery, categoryFilter } = get()

        // CV2.7: Apply search and category filters (AND logic).
        const query = searchQuery.trim().toLowerCase()
        const visibleCards = cards.filter((card) => {
            const matchesSearch = query === '' || card.name.toLowerCase().includes(query)
            const matchesCategory = categoryFilter === 'all' || card.category === categoryFilter
            return matchesSearch && matchesCategory
        })

        return visibleCards.map((card) => {
            const position = cardPositions[card.id] ?? { x: 0, y: 0 }
            return {
                id: card.id,
                type: 'componentCard' as const,
                position,
                data: {
                    card,
                    isSelected: selectedCardId === card.id,
                    canvasView,
                },
            }
        })
    },

    toFlowEdges: () => {
        const { cards, searchQuery, categoryFilter } = get()

        // CV2.7: Derive the visible card set using the same filter logic as toFlowNodes
        // so edges are only produced between cards that are currently rendered.
        const query = searchQuery.trim().toLowerCase()
        const visibleCards = cards.filter((card) => {
            const matchesSearch = query === '' || card.name.toLowerCase().includes(query)
            const matchesCategory = categoryFilter === 'all' || card.category === categoryFilter
            return matchesSearch && matchesCategory
        })

        // Build a lookup from importPath → card restricted to visible cards only.
        const byImportPath = new Map<string, ComponentCardData>()
        for (const card of visibleCards) {
            byImportPath.set(card.importPath, card)
        }

        const edges: Edge<DependencyEdgeData>[] = []
        for (const sourceCard of visibleCards) {
            if (!sourceCard.dependencies || sourceCard.dependencies.length === 0) continue

            for (const depPath of sourceCard.dependencies) {
                const targetCard = byImportPath.get(depPath)
                if (!targetCard) continue

                const edgeId = `dep-${sourceCard.id}-${targetCard.id}`
                edges.push({
                    id: edgeId,
                    source: sourceCard.id,
                    target: targetCard.id,
                    type: 'dependency',
                    data: {
                        targetGrade: targetCard.health?.grade ?? null,
                    },
                })
            }
        }
        return edges
    },
}))
