/**
 * Init command -- flint-ci/src/commands/init.ts
 *
 * Generates a starter flint.config.yaml for a project.
 * Detects existing design tokens and project structure to
 * provide sensible defaults.
 *
 * Exit codes: 0=created, 1=already exists (skip), 3=error.
 */

import fs from 'node:fs'
import path from 'node:path'
import { ANSI } from '../utils/ansi.js'

// ── Types ────────────────────────────────────────────────────────────────────

export interface InitOptions {
    projectRoot?: string
    force?: boolean  // overwrite existing
}

interface DetectedProject {
    name: string
    hasTokens: boolean
    tokenSource: string
    library: string
}

// ── Library detection ────────────────────────────────────────────────────────

/** Known design system libraries and their package.json identifiers. */
const LIBRARY_DETECTORS: Array<{ packages: string[]; library: string }> = [
    { packages: ['tailwindcss', '@tailwindcss/vite', '@tailwindcss/cli'], library: 'tailwind' },
    { packages: ['primeng', 'primereact', 'primevue'], library: 'primeng' },
    { packages: ['@shadcn/ui', 'shadcn-ui'], library: 'shadcn' },
    { packages: ['@mui/material', '@mui/system', '@emotion/react'], library: 'mui' },
    { packages: ['@chakra-ui/react'], library: 'chakra' },
    { packages: ['antd', '@ant-design/icons'], library: 'antd' },
]

/**
 * Reads package.json and detects the project name and design system library.
 * Returns sensible defaults if package.json is missing or unreadable.
 */
function detectProject(projectRoot: string): DetectedProject {
    const result: DetectedProject = {
        name: 'my-project',
        hasTokens: false,
        tokenSource: '.flint/design-tokens.json',
        library: 'auto',
    }

    // Check for design tokens
    const tokenPath = path.join(projectRoot, '.flint', 'design-tokens.json')
    if (fs.existsSync(tokenPath)) {
        result.hasTokens = true
        result.tokenSource = '.flint/design-tokens.json'
    }

    // Read package.json
    const pkgPath = path.join(projectRoot, 'package.json')
    let pkg: Record<string, unknown> | null = null
    try {
        if (fs.existsSync(pkgPath)) {
            const raw = fs.readFileSync(pkgPath, 'utf-8')
            pkg = JSON.parse(raw) as Record<string, unknown>
        }
    } catch {
        // Non-fatal: proceed with defaults
    }

    if (pkg) {
        // Extract project name
        if (typeof pkg.name === 'string' && pkg.name.length > 0) {
            result.name = pkg.name
        }

        // Detect library from dependencies + devDependencies
        const allDeps = new Set<string>()
        for (const key of ['dependencies', 'devDependencies', 'peerDependencies']) {
            const deps = pkg[key]
            if (deps && typeof deps === 'object') {
                for (const depName of Object.keys(deps as Record<string, unknown>)) {
                    allDeps.add(depName)
                }
            }
        }

        for (const detector of LIBRARY_DETECTORS) {
            if (detector.packages.some((p) => allDeps.has(p))) {
                result.library = detector.library
                break
            }
        }
    }

    return result
}

// ── YAML generation ──────────────────────────────────────────────────────────

/**
 * Generates a well-commented flint.config.yaml string from detected project info.
 */
function generateConfigYaml(project: DetectedProject): string {
    const libraryComment = project.library === 'auto'
        ? '# "auto" detects from package.json. Explicit options: tailwind, primeng, shadcn, mui, chakra, antd'
        : `# Detected "${project.library}" from package.json dependencies`

    const tokenComment = project.hasTokens
        ? '# Found existing tokens at this path'
        : '# Create this file or run `flint-gate sync` to pull from Figma'

    const lines = [
        '# ──────────────────────────────────────────────────────────────────────────────',
        '# Flint Governance Configuration',
        '# https://flint.dev/docs/config',
        '#',
        '# This file controls how Flint enforces design systems, accessibility,',
        '# and brand compliance in your project. Generated by `flint-gate init`.',
        '# ──────────────────────────────────────────────────────────────────────────────',
        '',
        '# Config schema version (do not change)',
        'schema_version: "1"',
        '',
        `# Project identifier`,
        `project: "${project.name}"`,
        '',
        '# Governance domain preset.',
        '# Options: general, healthcare, finance, ecommerce, government',
        'domain: "general"',
        '',
        '# ── Design Tokens ────────────────────────────────────────────────────────────',
        '',
        'tokens:',
        `  # Path to your W3C DTCG design tokens file`,
        `  ${tokenComment}`,
        `  source: "${project.tokenSource}"`,
        '',
        `  # Which component library to map tokens to`,
        `  ${libraryComment}`,
        `  library: "${project.library}"`,
        '',
        '# ── Governance Rules ─────────────────────────────────────────────────────────',
        '',
        'rules:',
        '  # Mithril: Design system drift detection (color, typography, spacing, shadow, opacity)',
        '  mithril:',
        '    # "normative" = warn on violations (recommended for onboarding)',
        '    # "coercive"  = block on violations (strict enforcement)',
        '    # "advisory"  = report only, never block',
        '    # "off"       = disable entirely',
        '    mode: "normative"',
        '',
        '    # CIEDE2000 perceptual color distance threshold.',
        '    # Colors within this deltaE are considered "close enough".',
        '    # 2.0 is the just-noticeable-difference threshold.',
        '    delta_e: 2.0',
        '',
        '  # Accessibility: WCAG 2.1 compliance (50 rules)',
        '  accessibility:',
        '    # Conformance level: "A", "AA", or "AAA"',
        '    level: "AA"',
        '',
        '    # Same mode options as mithril',
        '    mode: "normative"',
        '',
        '  # Export Gate: Controls when code can be shipped',
        '  export_gate:',
        '    # Block export if Mithril violations exist',
        '    block_on_mithril: true',
        '',
        '    # Block export if accessibility violations exist',
        '    block_on_a11y: true',
        '',
        '# ── Enforcement Points ───────────────────────────────────────────────────────',
        '# Define where governance decisions are enforced and what action to take.',
        '',
        'enforcement:',
        '  # Which decision points are active',
        '  decision_points:',
        '    - ci_gate',
        '',
        '  # Per-point configuration',
        '  points:',
        '    ci_gate:',
        '      # Block the CI pipeline on coercive-mode violations',
        '      block_on:',
        '        - coercive',
        '',
        '      # Warn (annotate) on normative-mode violations',
        '      warn_on:',
        '        - normative',
        '',
    ]

    return lines.join('\n')
}

// ── Main command ─────────────────────────────────────────────────────────────

export async function initCommand(opts: InitOptions): Promise<number> {
    const projectRoot = path.resolve(opts.projectRoot ?? process.cwd())
    const configPath = path.join(projectRoot, 'flint.config.yaml')
    const force = opts.force ?? false

    // Check if config already exists
    if (fs.existsSync(configPath) && !force) {
        console.log(
            `${ANSI.yellow}flint.config.yaml already exists at ${configPath}${ANSI.reset}`,
        )
        console.log(
            `${ANSI.dim}Use --force to overwrite.${ANSI.reset}`,
        )
        return 1
    }

    // Detect project info
    const project = detectProject(projectRoot)

    console.log(`${ANSI.dim}Detecting project structure...${ANSI.reset}`)
    console.log(`${ANSI.dim}  Project name:   ${project.name}${ANSI.reset}`)
    console.log(`${ANSI.dim}  Design tokens:  ${project.hasTokens ? 'found' : 'not found'}${ANSI.reset}`)
    console.log(`${ANSI.dim}  Library:        ${project.library}${ANSI.reset}`)
    console.log()

    // Generate config
    const yaml = generateConfigYaml(project)

    // Write to disk
    try {
        // Ensure parent directory exists (projectRoot should always exist,
        // but guard against edge cases)
        const dir = path.dirname(configPath)
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true })
        }

        fs.writeFileSync(configPath, yaml, 'utf-8')
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err)
        console.error(
            `${ANSI.red}Failed to write config: ${msg}${ANSI.reset}`,
        )
        return 3
    }

    // Print the generated config to stdout
    console.log(`${ANSI.bold}Generated flint.config.yaml:${ANSI.reset}`)
    console.log()
    console.log(`${ANSI.dim}${yaml}${ANSI.reset}`)

    // Print success and next steps
    console.log(`${ANSI.green}${ANSI.bold}Created ${configPath}${ANSI.reset}`)
    console.log()
    console.log(`${ANSI.bold}Next steps:${ANSI.reset}`)
    console.log()
    console.log(`  1. Review the generated ${ANSI.cyan}flint.config.yaml${ANSI.reset} and adjust rules to your team's standards.`)
    console.log()

    if (!project.hasTokens) {
        console.log(`  2. Add your design tokens to ${ANSI.cyan}.flint/design-tokens.json${ANSI.reset}`)
        console.log(`     or connect to Figma: ${ANSI.cyan}flint-gate sync${ANSI.reset}`)
        console.log()
        console.log(`  3. Run your first audit:`)
    } else {
        console.log(`  2. Run your first audit:`)
    }

    console.log(`     ${ANSI.cyan}npx flint-gate audit${ANSI.reset}`)
    console.log()
    console.log(`  Add to CI with the GitHub Action:`)
    console.log(`     ${ANSI.cyan}uses: Jtiem/flint-gate@v2${ANSI.reset}`)
    console.log()

    return 0
}
