/**
 * Kotlin Compose Emitter Tests -- flint-mcp/src/core/emitters/__tests__/kotlinEmitter.test.ts
 *
 * EXP.7: Tests for DTCG -> Kotlin Compose Color/Dp/Sp token emission.
 */

import { describe, it, expect } from 'vitest'
import { KotlinEmitter } from '../kotlinEmitter.js'
import type { DesignToken } from '../../../types.js'

function makeToken(overrides: Partial<DesignToken> & Pick<DesignToken, 'token_path' | 'token_type' | 'token_value'>): DesignToken {
    return {
        id: 1,
        description: null,
        collection_name: 'default',
        mode: 'Light',
        ...overrides,
    }
}

describe('KotlinEmitter', () => {
    const emitter = new KotlinEmitter()

    it('has correct platform and filename', () => {
        expect(emitter.platform).toBe('kotlin')
        expect(emitter.defaultFilename).toBe('Tokens.kt')
    })

    it('emits minimal valid output for empty tokens', () => {
        const result = emitter.emit([])
        expect(result.platform).toBe('kotlin')
        expect(result.tokenCount).toBe(0)
        expect(result.skippedTokens).toEqual([])
        expect(result.mimeType).toBe('text/x-kotlin')
        expect(result.code).toContain('// Generated by Flint EXP.7')
        expect(result.code).toContain('package com.project.tokens')
    })

    it('emits color tokens as Compose Color with ARGB hex', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'colors.primary.500', token_type: 'color', token_value: '#3B82F6' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(1)
        expect(result.code).toContain('object TokenColors {')
        expect(result.code).toContain('val Primary500 = Color(0xFF3B82F6)')
    })

    it('handles #RGB shorthand colors', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'colors.red', token_type: 'color', token_value: '#F00' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('Color(0xFFFF0000)')
    })

    it('handles #RRGGBBAA colors (converts to AARRGGBB)', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'colors.overlay', token_type: 'color', token_value: '#00000080' }),
        ]
        const result = emitter.emit(tokens)
        // #00000080 -> RRGGBB=000000, AA=80 -> 0x80000000
        expect(result.code).toContain('Color(0x80000000)')
    })

    it('emits spacing tokens as Dp values', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'spacing.sm', token_type: 'dimension', token_value: '8px' }),
            makeToken({ token_path: 'spacing.lg', token_type: 'dimension', token_value: '32px' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(2)
        expect(result.code).toContain('object TokenSpacing {')
        expect(result.code).toContain('val Sm = 8.dp')
        expect(result.code).toContain('val Lg = 32.dp')
    })

    it('emits font size dimensions as Sp values', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'typography.fontSize.heading1', token_type: 'dimension', token_value: '36px' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('object TokenTypography {')
        expect(result.code).toContain('val FontSizeHeading1 = 36.sp')
    })

    it('emits fontFamily tokens as const string values', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'typography.body', token_type: 'fontFamily', token_value: 'Inter, sans-serif' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(1)
        expect(result.code).toContain('const val Body = "Inter"')
    })

    it('emits fontWeight as const int values', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'typography.bold', token_type: 'fontWeight', token_value: '700' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('const val Bold = 700')
    })

    it('emits lineHeight and letterSpacing as Sp values', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'typography.lineHeight.normal', token_type: 'lineHeight', token_value: '1.5' }),
            makeToken({ token_path: 'typography.letterSpacing.wide', token_type: 'letterSpacing', token_value: '0.8px' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('val LineHeightNormal = 1.5.sp')
        expect(result.code).toContain('val LetterSpacingWide = 0.8.sp')
    })

    it('emits opacity tokens as float constants', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'opacity.disabled', token_type: 'opacity', token_value: '0.5' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('object TokenOpacity {')
        expect(result.code).toContain('const val Disabled = 0.5f')
    })

    it('converts token path to PascalCase identifier', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'colors.brand.primary', token_type: 'color', token_value: '#000' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('val BrandPrimary')
    })

    it('skips shadow tokens with explanation', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'shadows.sm', token_type: 'shadow', token_value: '0 1px 2px 0 rgba(0,0,0,0.05)' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(0)
        expect(result.skippedTokens).toHaveLength(1)
        expect(result.skippedTokens[0].reason).toContain('Modifier.shadow')
    })

    it('skips string and boolean types', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'misc.flag', token_type: 'boolean', token_value: 'true' }),
            makeToken({ token_path: 'misc.label', token_type: 'string', token_value: 'Hello' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(0)
        expect(result.skippedTokens).toHaveLength(2)
    })

    it('validates valid output successfully', () => {
        const result = emitter.emit([
            makeToken({ token_path: 'colors.red', token_type: 'color', token_value: '#FF0000' }),
        ])
        const validation = emitter.validate(result)
        expect(validation.valid).toBe(true)
        expect(validation.errors).toHaveLength(0)
    })

    it('uses custom package name from prefix option', () => {
        const result = emitter.emit(
            [makeToken({ token_path: 'colors.red', token_type: 'color', token_value: '#FF0000' })],
            { prefix: 'com.myapp.design' },
        )
        expect(result.code).toContain('package com.myapp.design')
    })

    it('includes correct imports based on token types', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'colors.red', token_type: 'color', token_value: '#FF0000' }),
            makeToken({ token_path: 'spacing.sm', token_type: 'dimension', token_value: '8px' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('import androidx.compose.ui.graphics.Color')
        expect(result.code).toContain('import androidx.compose.ui.unit.dp')
    })

    it('filters tokens by mode', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'colors.primary', token_type: 'color', token_value: '#3B82F6', mode: 'Light' }),
            makeToken({ token_path: 'colors.primary', token_type: 'color', token_value: '#1E40AF', mode: 'Dark' }),
        ]
        const result = emitter.emit(tokens, { mode: 'Dark' })
        expect(result.tokenCount).toBe(1)
        expect(result.code).toContain('0xFF1E40AF')
    })
})
