/**
 * React Native Emitter Tests -- flint-mcp/src/core/emitters/__tests__/reactNativeEmitter.test.ts
 *
 * EXP.7: Tests for DTCG -> React Native TypeScript token emission.
 */

import { describe, it, expect } from 'vitest'
import { ReactNativeEmitter } from '../reactNativeEmitter.js'
import type { DesignToken } from '../../../types.js'

function makeToken(overrides: Partial<DesignToken> & Pick<DesignToken, 'token_path' | 'token_type' | 'token_value'>): DesignToken {
    return {
        id: 1,
        description: null,
        collection_name: 'default',
        mode: 'Light',
        ...overrides,
    }
}

describe('ReactNativeEmitter', () => {
    const emitter = new ReactNativeEmitter()

    it('has correct platform and filename', () => {
        expect(emitter.platform).toBe('react-native')
        expect(emitter.defaultFilename).toBe('tokens.ts')
    })

    it('emits minimal valid output for empty tokens', () => {
        const result = emitter.emit([])
        expect(result.platform).toBe('react-native')
        expect(result.tokenCount).toBe(0)
        expect(result.skippedTokens).toEqual([])
        expect(result.mimeType).toBe('application/typescript')
        expect(result.code).toContain('// Generated by Flint EXP.7')
        expect(result.code).toContain("import { StyleSheet } from 'react-native'")
    })

    it('emits color tokens as hex string constants', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'colors.primary.500', token_type: 'color', token_value: '#3B82F6' }),
            makeToken({ token_path: 'colors.brand.secondary', token_type: 'color', token_value: '#9333EA' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(2)
        expect(result.code).toContain("primary500: '#3B82F6'")
        expect(result.code).toContain("brandSecondary: '#9333EA'")
        expect(result.code).toContain('export const colors = {')
    })

    it('emits spacing tokens with px stripped to numeric', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'spacing.sm', token_type: 'dimension', token_value: '8px' }),
            makeToken({ token_path: 'spacing.md', token_type: 'dimension', token_value: '16px' }),
            makeToken({ token_path: 'spacing.lg', token_type: 'dimension', token_value: '32px' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(3)
        expect(result.code).toContain('sm: 8,')
        expect(result.code).toContain('md: 16,')
        expect(result.code).toContain('lg: 32,')
        expect(result.code).toContain('export const spacing = {')
    })

    it('converts rem dimensions to numeric dp (16px base)', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'spacing.base', token_type: 'dimension', token_value: '1rem' }),
            makeToken({ token_path: 'spacing.large', token_type: 'dimension', token_value: '2rem' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('base: 16,')
        expect(result.code).toContain('large: 32,')
    })

    it('emits fontFamily tokens as string constants', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'typography.body', token_type: 'fontFamily', token_value: 'Inter, sans-serif' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(1)
        expect(result.code).toContain("body: 'Inter'")
        expect(result.code).toContain('export const typography = {')
    })

    it('emits fontWeight tokens as string values', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'typography.bold', token_type: 'fontWeight', token_value: '700' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain("bold: '700'")
    })

    it('emits lineHeight and letterSpacing as numeric values', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'typography.lineHeight.normal', token_type: 'lineHeight', token_value: '1.5' }),
            makeToken({ token_path: 'typography.letterSpacing.wide', token_type: 'letterSpacing', token_value: '0.8px' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('lineHeightNormal: 1.5,')
        expect(result.code).toContain('letterSpacingWide: 0.8,')
    })

    it('emits opacity tokens as numeric values', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'opacity.disabled', token_type: 'opacity', token_value: '0.5' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('disabled: 0.5,')
        expect(result.code).toContain('export const opacity = {')
    })

    it('converts token path to correct camelCase identifier', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'colors.primary.500', token_type: 'color', token_value: '#000' }),
        ]
        const result = emitter.emit(tokens)
        // 'colors.primary.500' -> drop 'colors' -> 'primary.500' -> 'primary500'
        expect(result.code).toContain('primary500:')
    })

    it('skips unsupported token types and records them', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'misc.flag', token_type: 'boolean', token_value: 'true' }),
            makeToken({ token_path: 'misc.label', token_type: 'string', token_value: 'Hello' }),
            makeToken({ token_path: 'colors.ok', token_type: 'color', token_value: '#FFF' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(1)
        expect(result.skippedTokens).toHaveLength(2)
        expect(result.skippedTokens[0].tokenPath).toBe('misc.flag')
        expect(result.skippedTokens[0].tokenType).toBe('boolean')
        expect(result.skippedTokens[0].reason).toContain('not supported')
        expect(result.skippedTokens[1].tokenPath).toBe('misc.label')
    })

    it('validates valid output successfully', () => {
        const result = emitter.emit([
            makeToken({ token_path: 'colors.red', token_type: 'color', token_value: '#FF0000' }),
        ])
        const validation = emitter.validate(result)
        expect(validation.valid).toBe(true)
        expect(validation.errors).toHaveLength(0)
    })

    it('filters tokens by mode when option is provided', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'colors.primary', token_type: 'color', token_value: '#3B82F6', mode: 'Light' }),
            makeToken({ token_path: 'colors.primary', token_type: 'color', token_value: '#1E40AF', mode: 'Dark' }),
        ]
        const result = emitter.emit(tokens, { mode: 'Dark' })
        expect(result.tokenCount).toBe(1)
        expect(result.code).toContain('#1E40AF')
        expect(result.code).not.toContain('#3B82F6')
    })

    it('emits shadow tokens into shadows object', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'shadows.sm', token_type: 'shadow', token_value: '0 1px 2px 0 rgba(0, 0, 0, 0.05)' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(1)
        expect(result.code).toContain('export const shadows = {')
        expect(result.code).toContain('shadowColor:')
        expect(result.code).toContain('shadowOffset:')
    })
})
