/**
 * Swift Emitter Tests -- flint-mcp/src/core/emitters/__tests__/swiftEmitter.test.ts
 *
 * EXP.7: Tests for DTCG -> Swift UIColor/CGFloat token emission.
 */

import { describe, it, expect } from 'vitest'
import { SwiftEmitter } from '../swiftEmitter.js'
import type { DesignToken } from '../../../types.js'

function makeToken(overrides: Partial<DesignToken> & Pick<DesignToken, 'token_path' | 'token_type' | 'token_value'>): DesignToken {
    return {
        id: 1,
        description: null,
        collection_name: 'default',
        mode: 'Light',
        ...overrides,
    }
}

describe('SwiftEmitter', () => {
    const emitter = new SwiftEmitter()

    it('has correct platform and filename', () => {
        expect(emitter.platform).toBe('swift')
        expect(emitter.defaultFilename).toBe('Tokens.swift')
    })

    it('emits minimal valid output for empty tokens', () => {
        const result = emitter.emit([])
        expect(result.platform).toBe('swift')
        expect(result.tokenCount).toBe(0)
        expect(result.skippedTokens).toEqual([])
        expect(result.mimeType).toBe('text/x-swift')
        expect(result.code).toContain('// Generated by Flint EXP.7')
        expect(result.code).toContain('import UIKit')
    })

    it('emits color tokens as UIColor with correct RGB values', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'colors.primary.500', token_type: 'color', token_value: '#3B82F6' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(1)
        expect(result.code).toContain('extension UIColor {')
        // #3B = 59/255 = 0.231, #82 = 130/255 = 0.510, #F6 = 246/255 = 0.965
        expect(result.code).toContain('static let primary500 = UIColor(red: 0.231')
        expect(result.code).toContain('green: 0.51')
        expect(result.code).toContain('blue: 0.965')
        expect(result.code).toContain('alpha: 1.0)')
    })

    it('handles #RGB shorthand colors', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'colors.red', token_type: 'color', token_value: '#F00' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('red: 1.0')
        expect(result.code).toContain('green: 0.0')
        expect(result.code).toContain('blue: 0.0')
    })

    it('handles #RRGGBBAA colors with alpha', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'colors.overlay', token_type: 'color', token_value: '#00000080' }),
        ]
        const result = emitter.emit(tokens)
        // Alpha: 0x80 = 128/255 ~= 0.502
        expect(result.code).toContain('alpha: 0.502')
    })

    it('emits spacing tokens as CGFloat constants', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'spacing.sm', token_type: 'dimension', token_value: '8px' }),
            makeToken({ token_path: 'spacing.lg', token_type: 'dimension', token_value: '32px' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(2)
        expect(result.code).toContain('enum Spacing {')
        expect(result.code).toContain('static let sm: CGFloat = 8.0')
        expect(result.code).toContain('static let lg: CGFloat = 32.0')
    })

    it('emits fontFamily tokens as string constants', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'typography.body', token_type: 'fontFamily', token_value: 'Inter' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(1)
        expect(result.code).toContain('enum Typography {')
        expect(result.code).toContain('static let body = "Inter"')
    })

    it('emits fontWeight as CGFloat constants', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'typography.bold', token_type: 'fontWeight', token_value: '700' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('static let bold: CGFloat = 700.0')
    })

    it('emits lineHeight and letterSpacing as CGFloat', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'typography.lineHeight.normal', token_type: 'lineHeight', token_value: '1.5' }),
            makeToken({ token_path: 'typography.letterSpacing.wide', token_type: 'letterSpacing', token_value: '0.8px' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('static let lineHeightNormal: CGFloat = 1.5')
        expect(result.code).toContain('static let letterSpacingWide: CGFloat = 0.8')
    })

    it('emits opacity tokens as CGFloat', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'opacity.disabled', token_type: 'opacity', token_value: '0.5' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('enum Opacity {')
        expect(result.code).toContain('static let disabled: CGFloat = 0.5')
    })

    it('converts token path to correct camelCase identifier', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'colors.brand.primary', token_type: 'color', token_value: '#000' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.code).toContain('static let brandPrimary')
    })

    it('skips shadow tokens with explanation', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'shadows.sm', token_type: 'shadow', token_value: '0 1px 2px 0 rgba(0,0,0,0.05)' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(0)
        expect(result.skippedTokens).toHaveLength(1)
        expect(result.skippedTokens[0].reason).toContain('NSShadow')
    })

    it('skips string and boolean types', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'misc.flag', token_type: 'boolean', token_value: 'true' }),
            makeToken({ token_path: 'misc.label', token_type: 'string', token_value: 'Hello' }),
        ]
        const result = emitter.emit(tokens)
        expect(result.tokenCount).toBe(0)
        expect(result.skippedTokens).toHaveLength(2)
    })

    it('validates valid output successfully', () => {
        const result = emitter.emit([
            makeToken({ token_path: 'colors.red', token_type: 'color', token_value: '#FF0000' }),
        ])
        const validation = emitter.validate(result)
        expect(validation.valid).toBe(true)
        expect(validation.errors).toHaveLength(0)
    })

    it('filters tokens by mode and collection', () => {
        const tokens: DesignToken[] = [
            makeToken({ token_path: 'colors.primary', token_type: 'color', token_value: '#3B82F6', mode: 'Light', collection_name: 'brand' }),
            makeToken({ token_path: 'colors.primary', token_type: 'color', token_value: '#1E40AF', mode: 'Dark', collection_name: 'brand' }),
            makeToken({ token_path: 'colors.accent', token_type: 'color', token_value: '#EF4444', mode: 'Light', collection_name: 'other' }),
        ]
        const result = emitter.emit(tokens, { mode: 'Light', collection: 'brand' })
        expect(result.tokenCount).toBe(1)
        // #3B82F6 -> red: 0.231 (Swift converts hex to UIColor float channels)
        expect(result.code).toContain('red: 0.231')
        // Only 1 color entry; Dark and other collection should be filtered out
        expect(result.code).not.toContain('red: 0.118')  // #1E40AF
        expect(result.code).not.toContain('red: 0.937')  // #EF4444
    })
})
