/**
 * dbomService.ts — flint-mcp/src/core/governance/dbomService.ts
 *
 * Governance-enriched Design Bill of Materials (DBOM) generator.
 *
 * Wraps the core DBOM generator (flint-mcp/src/core/dbom/generator.ts) and
 * enriches it with:
 *   - Per-token compliance status (compliant / drifted / unknown)
 *   - Per-component mutation provenance (when includeProvenance=true)
 *   - Compliance-by-authority breakdown from GOV.1 rule provenance
 *   - Component source inference (figma / flint / handwritten)
 *   - CycloneDX-extended output format (when format='cyclonedx')
 *   - Writes to .flint/dbom.json unless dryRun=true
 *
 * Phase: DBOM.1 (Design Bill of Materials)
 */

import fs from 'node:fs'
import path from 'node:path'
import BetterSqlite3 from 'better-sqlite3'
import { generateDBOM as generateCoreDBOM } from '../dbom/generator.js'
import { buildComplianceSummary } from './ruleProvenanceRegistry.js'
import { loadProjectContext } from '../projectContext.js'
import type { DesignBillOfMaterials } from '../dbom/types.js'
import type {
    DBOM,
    DBOMOptions,
    DBOMTokenEntry,
    DBOMComponentEntry,
    DBOMComponentProvenance,
    DBOMPosture,
    SourceAuthority,
} from './types.js'

// ── Constants ────────────────────────────────────────────────────────────────

const FLINT_VERSION = '1.0.0'

// ── Provenance helpers ───────────────────────────────────────────────────────

interface ProvenanceRow {
    provenance_source: string
    cnt: number
}

interface ProvenanceLatestRow {
    latest: string | null
}

/**
 * Query provenance DB for per-file mutation breakdown.
 * Returns null if the DB does not exist or any error occurs. Never throws.
 */
function queryFileProvenance(
    projectRoot: string,
    filePath: string,
): DBOMComponentProvenance | null {
    try {
        const dbPath = path.join(projectRoot, '.flint', 'provenance.db')
        if (!fs.existsSync(dbPath)) return null

        const db = new BetterSqlite3(dbPath, { readonly: true })
        try {
            // Check that both tables exist
            const tableCheck = db
                .prepare(
                    `SELECT name FROM sqlite_master
                     WHERE type='table' AND name IN ('mutation_provenance', 'mutations_ledger')`,
                )
                .all() as Array<{ name: string }>

            if (tableCheck.length < 2) return null

            // Count by source for this file
            const rows = db
                .prepare(
                    `SELECT mp.provenance_source, COUNT(*) AS cnt
                     FROM mutation_provenance mp
                     INNER JOIN mutations_ledger ml ON mp.mutation_id = ml.id
                     WHERE ml.file_path = ?
                     GROUP BY mp.provenance_source`,
                )
                .all(filePath) as ProvenanceRow[]

            const bySource: Record<string, number> = {}
            let totalMutations = 0
            for (const row of rows) {
                bySource[row.provenance_source] = row.cnt
                totalMutations += row.cnt
            }

            // Latest mutation timestamp
            const latestRow = db
                .prepare(
                    `SELECT MAX(mp.timestamp) AS latest
                     FROM mutation_provenance mp
                     INNER JOIN mutations_ledger ml ON mp.mutation_id = ml.id
                     WHERE ml.file_path = ?`,
                )
                .get(filePath) as ProvenanceLatestRow | undefined

            return {
                totalMutations,
                bySource,
                lastMutatedAt: latestRow?.latest ?? null,
            }
        } finally {
            db.close()
        }
    } catch {
        return null
    }
}

// ── Component source inference ───────────────────────────────────────────────

/**
 * Infers the origin of a component by checking:
 *   1. If provenance shows 'import' source -> 'figma'
 *   2. If the file was created by Flint scaffolding -> 'flint'
 *   3. Otherwise -> 'handwritten'
 *
 * When provenance is unavailable, falls back to filename heuristics:
 *   - Files under an ingestion/ or figma/ directory -> 'figma'
 *   - Files generated by scaffolding (template markers) -> 'flint'
 */
function inferComponentSource(
    filePath: string,
    provenance: DBOMComponentProvenance | null,
): 'figma' | 'flint' | 'handwritten' {
    // If provenance data exists, use it
    if (provenance !== null && provenance.totalMutations > 0) {
        const importCount = provenance.bySource['import'] ?? 0
        const autoHealCount = provenance.bySource['auto-heal'] ?? 0
        if (importCount > 0 || autoHealCount > 0) return 'figma'

        const humanCount = provenance.bySource['human'] ?? 0
        const agentCount = provenance.bySource['agent'] ?? 0
        if (agentCount > humanCount) return 'flint'
    }

    // Filename heuristics
    const lower = filePath.toLowerCase()
    if (lower.includes('/figma/') || lower.includes('/ingestion/') || lower.includes('.figma.')) {
        return 'figma'
    }
    if (lower.includes('/generated/') || lower.includes('/scaffold/')) {
        return 'flint'
    }

    return 'handwritten'
}

// ── Token compliance classification ─────────────────────────────────────────

/**
 * Determines compliance status for a token based on whether any violations
 * reference its domain.
 *
 *   - 'compliant'  — token is used and no violations in its domain
 *   - 'drifted'    — at least one violation detected for a value this token governs
 *   - 'unknown'    — token is not used anywhere (dead token)
 */
function classifyTokenCompliance(
    tokenPath: string,
    tokenType: string,
    usedInFiles: string[],
    coreDBOM: DesignBillOfMaterials,
): 'compliant' | 'drifted' | 'unknown' {
    if (usedInFiles.length === 0) return 'unknown'

    // Check if any component that uses this token has violations in the same domain
    const tokenDomain = mapTokenTypeToDomain(tokenType)

    for (const comp of coreDBOM.components) {
        const relativePath = path.relative(coreDBOM.projectRoot, comp.filePath)
        if (!usedInFiles.includes(relativePath)) continue

        // Check Mithril violations in the same domain
        for (const v of comp.violations) {
            const violationDomain = extractViolationDomain(v.ruleId)
            if (violationDomain === tokenDomain) return 'drifted'
        }
    }

    return 'compliant'
}

/**
 * Maps a token type string to a violation domain for cross-referencing.
 */
function mapTokenTypeToDomain(tokenType: string): string {
    const lower = tokenType.toLowerCase()
    if (lower === 'color' || lower.includes('color')) return 'color'
    if (lower === 'dimension' || lower === 'spacing' || lower.includes('size')) return 'spacing'
    if (lower.includes('font') || lower === 'typography') return 'typography'
    if (lower.includes('shadow') || lower === 'boxShadow') return 'shadow'
    if (lower.includes('opacity')) return 'opacity'
    return 'other'
}

/**
 * Extracts the violation domain from a Mithril rule ID.
 */
function extractViolationDomain(ruleId: string): string {
    if (ruleId.startsWith('MITHRIL-COL') || ruleId.includes('COLOR')) return 'color'
    if (ruleId.startsWith('MITHRIL-TYP') || ruleId.includes('TYP')) return 'typography'
    if (ruleId.startsWith('MITHRIL-SPC') || ruleId.includes('SPC')) return 'spacing'
    if (ruleId.startsWith('MITHRIL-SHD') || ruleId.includes('SHD')) return 'shadow'
    if (ruleId.startsWith('MITHRIL-OPC') || ruleId.includes('OPC')) return 'opacity'
    return 'other'
}

// ── CycloneDX format ────────────────────────────────────────────────────────

interface CycloneDXEnvelope {
    bomFormat: 'CycloneDX'
    specVersion: '1.5'
    serialNumber: string
    version: 1
    metadata: {
        timestamp: string
        tools: Array<{ vendor: string; name: string; version: string }>
        component: { type: string; name: string; version: string }
    }
    components: Array<{
        type: string
        name: string
        version: string
        purl?: string
        properties: Array<{ name: string; value: string }>
    }>
    properties: Array<{ name: string; value: string }>
}

/**
 * Wraps a DBOM in a CycloneDX 1.5 extended envelope.
 */
function wrapCycloneDX(dbom: DBOM): CycloneDXEnvelope {
    const serialNumber = `urn:uuid:${generateUUID()}`

    return {
        bomFormat: 'CycloneDX',
        specVersion: '1.5',
        serialNumber,
        version: 1,
        metadata: {
            timestamp: dbom.generatedAt,
            tools: [
                {
                    vendor: 'Flint',
                    name: 'flint-mcp',
                    version: FLINT_VERSION,
                },
            ],
            component: {
                type: 'application',
                name: path.basename(dbom.projectRoot),
                version: '0.0.0',
            },
        },
        components: dbom.components.map((comp) => ({
            type: 'library',
            name: comp.name,
            version: '0.0.0',
            properties: [
                { name: 'flint:filePath', value: comp.filePath },
                { name: 'flint:source', value: comp.source },
                { name: 'flint:violations', value: String(comp.auditResult.violations) },
                { name: 'flint:score', value: String(comp.auditResult.score) },
            ],
        })),
        properties: [
            { name: 'flint:healthScore', value: String(dbom.posture.healthScore) },
            { name: 'flint:grade', value: dbom.posture.grade },
            { name: 'flint:totalViolations', value: String(dbom.posture.totalViolations) },
            { name: 'flint:dbom', value: JSON.stringify(dbom) },
        ],
    }
}

/**
 * Simple UUID v4 generator (no crypto dependency needed for non-security use).
 */
function generateUUID(): string {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
        const r = (Math.random() * 16) | 0
        const v = c === 'x' ? r : (r & 0x3) | 0x8
        return v.toString(16)
    })
}

// ── Main generator ──────────────────────────────────────────────────────────

/**
 * Generate a governance-enriched Design Bill of Materials.
 *
 * 1. Delegates to the core DBOM generator for token inventory + linter analysis.
 * 2. Enriches with: token compliance status, component provenance, compliance
 *    by authority, component source inference.
 * 3. Optionally wraps in CycloneDX envelope.
 * 4. Writes to .flint/dbom.json unless dryRun=true.
 *
 * @param projectRoot  Absolute path to the project root.
 * @param options      Generation options (format, includeProvenance, dryRun).
 * @returns            The governance-enriched DBOM.
 */
export async function generateDBOM(
    projectRoot: string,
    options: DBOMOptions = {},
): Promise<DBOM> {
    const { includeProvenance = false, dryRun = false, glob } = options

    const generatedAt = new Date().toISOString()

    // ── 1. Generate core DBOM ────────────────────────────────────────────────
    const coreDBOM = await generateCoreDBOM(projectRoot, glob)

    // ── 2. Build token entries with compliance status ────────────────────────
    const tokens: DBOMTokenEntry[] = coreDBOM.tokens.map((tok) => ({
        name: tok.path,
        value: tok.value,
        category: tok.type,
        usedInFiles: tok.usedIn,
        complianceStatus: classifyTokenCompliance(
            tok.path,
            tok.type,
            tok.usedIn,
            coreDBOM,
        ),
    }))

    // ── 3. Build component entries with provenance ───────────────────────────
    const components: DBOMComponentEntry[] = coreDBOM.components.map((comp) => {
        const totalViolations = comp.violations.length + comp.a11yViolations.length
        // Per-component health: 100 - (criticals * 10 + warnings * 3)
        const criticals =
            comp.a11yViolations.length +
            comp.violations.filter((v) => v.severity === 'critical').length
        const warnings = comp.violations.filter((v) => v.severity === 'amber').length
        const score = Math.max(0, Math.min(100, 100 - (criticals * 10 + warnings * 3)))

        let provenance: DBOMComponentProvenance | undefined
        if (includeProvenance) {
            const fileProvenance = queryFileProvenance(projectRoot, comp.filePath)
            provenance = fileProvenance ?? {
                totalMutations: 0,
                bySource: {},
                lastMutatedAt: null,
            }
        }

        return {
            name: comp.name,
            filePath: comp.filePath,
            source: inferComponentSource(
                comp.filePath,
                includeProvenance
                    ? (provenance ?? queryFileProvenance(projectRoot, comp.filePath))
                    : queryFileProvenance(projectRoot, comp.filePath),
            ),
            auditResult: {
                violations: totalViolations,
                score,
            },
            ...(provenance !== undefined ? { provenance } : {}),
        }
    })

    // ── 4. Build compliance by authority ──────────────────────────────────────
    const allViolations: Array<{ ruleId: string; severity: string }> = []
    for (const comp of coreDBOM.components) {
        for (const v of comp.violations) {
            allViolations.push({ ruleId: v.ruleId, severity: v.severity })
        }
        for (const v of comp.a11yViolations) {
            allViolations.push({ ruleId: v.ruleId, severity: 'critical' })
        }
    }

    const complianceSummary = buildComplianceSummary(allViolations)
    const complianceByAuthority: Record<string, number> = {}
    for (const [authority, count] of Object.entries(complianceSummary.byAuthority)) {
        if (count > 0) {
            complianceByAuthority[authority] = count
        }
    }

    // ── 5. Build posture ─────────────────────────────────────────────────────
    const posture: DBOMPosture = {
        healthScore: coreDBOM.summary.healthScore,
        grade: coreDBOM.summary.grade,
        totalTokens: coreDBOM.summary.totalTokens,
        totalComponents: coreDBOM.summary.totalComponents,
        totalViolations: allViolations.length,
        complianceByAuthority,
    }

    // ── 6. Build summary string ──────────────────────────────────────────────
    const summary = buildSummaryString(posture, components.length, tokens.length)

    // ── 7. Assemble DBOM ─────────────────────────────────────────────────────
    const dbom: DBOM = {
        version: '1.0',
        generatedAt,
        flintVersion: FLINT_VERSION,
        projectRoot,
        posture,
        tokens,
        components,
        summary,
    }

    // ── 8. Write to disk ─────────────────────────────────────────────────────
    if (!dryRun) {
        const flintDir = path.join(projectRoot, '.flint')
        if (!fs.existsSync(flintDir)) {
            fs.mkdirSync(flintDir, { recursive: true })
        }
        const outputPath = path.join(flintDir, 'dbom.json')
        const tmpPath = outputPath + '.tmp'
        fs.writeFileSync(tmpPath, JSON.stringify(dbom, null, 2), 'utf-8')
        fs.renameSync(tmpPath, outputPath)
    }

    return dbom
}

/**
 * Build a plain-English summary of the DBOM.
 */
function buildSummaryString(
    posture: DBOMPosture,
    componentCount: number,
    tokenCount: number,
): string {
    const status =
        posture.totalViolations === 0
            ? 'fully compliant'
            : posture.healthScore >= 80
                ? `mostly compliant with ${posture.totalViolations} violation(s)`
                : `non-compliant with ${posture.totalViolations} violation(s)`

    return (
        `Project is ${status} — ` +
        `${componentCount} component(s), ${tokenCount} token(s), ` +
        `health score ${posture.healthScore}/100 (grade ${posture.grade}).`
    )
}

/**
 * Format the DBOM according to the requested output format.
 * Returns a JSON string (either raw DBOM or CycloneDX envelope).
 */
export function formatDBOMOutput(
    dbom: DBOM,
    format: 'json' | 'cyclonedx' = 'json',
): string {
    if (format === 'cyclonedx') {
        return JSON.stringify(wrapCycloneDX(dbom), null, 2)
    }
    return JSON.stringify(dbom, null, 2)
}
