/**
 * GovernanceEventService — flint-mcp/src/core/governance/eventService.ts
 *
 * Provides CRUD and aggregation operations over the governance_events table.
 * Accepts a better-sqlite3 Database instance in its constructor so tests can
 * inject an in-memory database without touching the filesystem.
 *
 * All timestamps are ISO 8601 UTC strings (e.g. "2026-03-14T21:00:00.000Z").
 * The metadata column is stored as a JSON string and parsed/stringified here.
 *
 * This module runs in the MCP server process (Node.js). It MUST NOT be
 * imported anywhere inside src/ (process boundary law).
 */

import type Database from 'better-sqlite3'
import type { GovernanceEvent, EventFilters } from './types.js'

// ── Row shape as stored in SQLite ─────────────────────────────────────────────

interface EventRow {
    id: string
    timestamp: string
    event_type: string
    rule_id: string
    severity: string
    node_id: string | null
    file_path: string
    message: string | null
    session_id: string | null
    actor: string
    metadata: string
}

// ── DDL ───────────────────────────────────────────────────────────────────────

const DDL = `
CREATE TABLE IF NOT EXISTS governance_events (
    id          TEXT    PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    timestamp   TEXT    NOT NULL    DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    event_type  TEXT    NOT NULL    CHECK (event_type IN ('violation', 'override', 'export_block', 'auto_fix', 'rule_change', 'token_extraction')),
    rule_id     TEXT    NOT NULL,
    severity    TEXT    NOT NULL    CHECK (severity IN ('critical', 'warning', 'info')),
    node_id     TEXT,
    file_path   TEXT    NOT NULL,
    message     TEXT,
    session_id  TEXT,
    actor       TEXT    NOT NULL    DEFAULT 'system',
    metadata    TEXT    NOT NULL    DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_gov_events_timestamp ON governance_events(timestamp);
CREATE INDEX IF NOT EXISTS idx_gov_events_rule      ON governance_events(rule_id);
CREATE INDEX IF NOT EXISTS idx_gov_events_file      ON governance_events(file_path);
CREATE INDEX IF NOT EXISTS idx_gov_events_type      ON governance_events(event_type);
`

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Convert a snake_case EventRow from the database into a camelCase GovernanceEvent. */
function rowToEvent(row: EventRow): GovernanceEvent {
    return {
        id: row.id,
        timestamp: row.timestamp,
        eventType: row.event_type as GovernanceEvent['eventType'],
        ruleId: row.rule_id,
        severity: row.severity as GovernanceEvent['severity'],
        nodeId: row.node_id ?? undefined,
        filePath: row.file_path,
        message: row.message ?? undefined,
        sessionId: row.session_id ?? undefined,
        actor: row.actor,
        metadata: JSON.parse(row.metadata) as Record<string, unknown>,
    }
}

// ── Service ───────────────────────────────────────────────────────────────────

export class GovernanceEventService {
    private readonly db: Database.Database

    /**
     * @param db - An open better-sqlite3 Database instance. Pass `new Database(':memory:')`
     *   in tests; pass the shared app database instance in production.
     */
    constructor(db: Database.Database) {
        this.db = db
        this.db.exec(DDL)
    }

    // ── Write ──────────────────────────────────────────────────────────────────

    /**
     * Insert a governance event row. The `id` and `timestamp` fields are
     * generated by SQLite defaults when omitted; if the caller supplies values
     * they are used as-is (useful for deterministic tests).
     */
    recordEvent(event: Omit<GovernanceEvent, 'id' | 'timestamp'> & { id?: string; timestamp?: string }): void {
        const id = event.id ?? null
        const timestamp = event.timestamp ?? null

        this.db.prepare<[
            string | null,
            string | null,
            string,
            string,
            string,
            string | null,
            string,
            string | null,
            string | null,
            string,
            string,
        ]>(`
            INSERT INTO governance_events
                (id, timestamp, event_type, rule_id, severity, node_id, file_path, message, session_id, actor, metadata)
            VALUES
                (
                    COALESCE(?, lower(hex(randomblob(16)))),
                    COALESCE(?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
                    ?, ?, ?, ?, ?, ?, ?, ?, ?
                )
        `).run(
            id,
            timestamp,
            event.eventType,
            event.ruleId,
            event.severity,
            event.nodeId ?? null,
            event.filePath,
            event.message ?? null,
            event.sessionId ?? null,
            event.actor,
            JSON.stringify(event.metadata),
        )
    }

    // ── Read ───────────────────────────────────────────────────────────────────

    /**
     * Query events with optional filters. All filters are ANDed together.
     * Defaults: no filter, limit 100, offset 0.
     */
    queryEvents(filters: EventFilters = {}): GovernanceEvent[] {
        const conditions: string[] = []
        const params: unknown[] = []

        if (filters.since) {
            conditions.push('timestamp >= ?')
            params.push(filters.since)
        }
        if (filters.until) {
            conditions.push('timestamp <= ?')
            params.push(filters.until)
        }
        if (filters.ruleId) {
            conditions.push('rule_id = ?')
            params.push(filters.ruleId)
        }
        if (filters.eventType) {
            conditions.push('event_type = ?')
            params.push(filters.eventType)
        }
        if (filters.filePath) {
            conditions.push('file_path = ?')
            params.push(filters.filePath)
        }
        if (filters.severity) {
            conditions.push('severity = ?')
            params.push(filters.severity)
        }

        const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : ''
        const limit = filters.limit ?? 100
        const offset = filters.offset ?? 0

        params.push(limit, offset)

        const rows = this.db.prepare<unknown[], EventRow>(`
            SELECT id, timestamp, event_type, rule_id, severity, node_id,
                   file_path, message, session_id, actor, metadata
            FROM governance_events
            ${where}
            ORDER BY timestamp DESC
            LIMIT ? OFFSET ?
        `).all(...params)

        return rows.map(rowToEvent)
    }

    /**
     * Count events grouped by event_type since a given ISO 8601 timestamp.
     * Returns an object keyed by event_type with integer counts.
     */
    getEventCounts(since: string): Record<string, number> {
        const rows = this.db.prepare<[string], { event_type: string; count: number }>(`
            SELECT event_type, COUNT(*) AS count
            FROM governance_events
            WHERE timestamp >= ?
            GROUP BY event_type
        `).all(since)

        const result: Record<string, number> = {}
        for (const row of rows) {
            result[row.event_type] = row.count
        }
        return result
    }

    /**
     * Return the top N most-violated rule IDs (highest violation count first).
     */
    getTopViolatedRules(limit: number): Array<{ ruleId: string; count: number }> {
        const rows = this.db.prepare<[number], { rule_id: string; count: number }>(`
            SELECT rule_id, COUNT(*) AS count
            FROM governance_events
            WHERE event_type = 'violation'
            GROUP BY rule_id
            ORDER BY count DESC
            LIMIT ?
        `).all(limit)

        return rows.map((row) => ({ ruleId: row.rule_id, count: row.count }))
    }

    /**
     * Return the top N files with the most violation events (highest count first).
     */
    getTopViolatedFiles(limit: number): Array<{ filePath: string; count: number }> {
        const rows = this.db.prepare<[number], { file_path: string; count: number }>(`
            SELECT file_path, COUNT(*) AS count
            FROM governance_events
            WHERE event_type = 'violation'
            GROUP BY file_path
            ORDER BY count DESC
            LIMIT ?
        `).all(limit)

        return rows.map((row) => ({ filePath: row.file_path, count: row.count }))
    }

    /**
     * Return the number of 'override' events for the given sessionId.
     * Uses a single COUNT query for efficiency (GOV.2).
     *
     * @param sessionId - The session UUID to scope the count to.
     *   Pass null / undefined to count across all sessions.
     */
    getOverrideCount(sessionId?: string | null): number {
        if (sessionId !== undefined && sessionId !== null) {
            const row = this.db.prepare<[string, string], { count: number }>(`
                SELECT COUNT(*) AS count
                FROM governance_events
                WHERE event_type = ? AND session_id = ?
            `).get('override', sessionId)
            return row?.count ?? 0
        }

        const row = this.db.prepare<[string], { count: number }>(`
            SELECT COUNT(*) AS count
            FROM governance_events
            WHERE event_type = ?
        `).get('override')
        return row?.count ?? 0
    }

    /**
     * Delete events with a timestamp strictly older than the given ISO 8601
     * string. Returns the number of rows deleted.
     */
    pruneEvents(olderThan: string): number {
        const result = this.db.prepare<[string]>(`
            DELETE FROM governance_events WHERE timestamp < ?
        `).run(olderThan)

        return result.changes
    }
}
