import type { ReviewReport, ReviewFinding } from '../../shared/review-schema';
import { countFindings, deriveVerdict } from '../../shared/review-schema';

const findings: ReviewFinding[] = [
  {
    id: 'WARN-1',
    title: '`as unknown as Map<string, string>` triple-cast in GovernanceDashboard hides setter type',
    severity: 'warning',
    evidence: [
      {
        file: 'src/components/ui/GovernanceDashboard.tsx',
        line: 466,
        excerpt: "onDefer={(key, d) => defer.setDeferDurations(((prev: Map<string, string>) => new Map([...prev, [key, d]])) as unknown as Map<string, string>)}",
        note: 'Setter is Dispatch<SetStateAction<Map<string,string>>>; updater function does not need a cast.',
      },
      { file: 'src/components/ui/GovernanceDashboard.tsx', line: 467 },
      { file: 'src/components/ui/GovernanceDashboard.tsx', line: 468 },
      { file: 'src/hooks/useGovernanceDefer.ts', line: 92, note: 'useState<Map<string,string>> setter origin' },
    ],
    observed: 'Three call sites cast a `(prev) => new Map(...)` updater function as `Map<string,string>` to satisfy the setter signature.',
    rationale: 'Runtime is correct (React detects function vs value), but the cast pattern teaches future contributors that `as unknown as X` is the way to satisfy a useState setter, masking whatever narrowing in the hook return type is the real cause. The natural updater signature compiles without any cast.',
    proposedFix: 'Remove all three casts: `defer.setDeferDurations(prev => new Map([...prev, [key, d]]))`. If TS errors, fix the hook return-type narrowing instead of casting through it.',
    scope: 'one-line',
    status: 'open',
    commandment: 16,
  },
  {
    id: 'WARN-2',
    title: 'tsconfig.tests.json relaxes noUnusedLocals/Parameters without an explanatory comment',
    severity: 'warning',
    evidence: [
      { file: 'tsconfig.tests.json', line: 5, excerpt: '"noUnusedLocals": false,' },
      { file: 'tsconfig.tests.json', line: 6, excerpt: '"noUnusedParameters": false,' },
      { file: 'tsconfig.app.json', line: 43, note: 'src/**/__tests__/** excluded — partition is correct' },
    ],
    observed: 'Test config disables two strict-lint flags that production config keeps on. The exclude/include partition is clean.',
    rationale: 'Defensible scope reduction (it.todo scaffolds and mock-fn parameter shapes legitimately produce unused symbols), but without a comment the next "tightening" PR will turn the flags back on and break 100 test files. Self-documenting configs survive churn.',
    proposedFix: 'Add a 3-line JSONC header comment to tsconfig.tests.json explaining why these two flags are off and that production keeps them on.',
    scope: 'one-line',
    status: 'open',
  },
  {
    id: 'WARN-3',
    title: 'LegacyFlintContract grandfather types are not enforced — new contracts may import them',
    severity: 'warning',
    evidence: [
      { file: 'shared/contract-schema.ts', line: 240, excerpt: 'export interface LegacyFlintContract extends Omit<FlintContract, ...>' },
      { file: 'shared/contract-schema.ts', line: 145, note: 'JSDoc says "for historical contracts only" but no lint rule enforces it' },
    ],
    observed: 'Four `Legacy*` types added to contract-schema.ts to let pre-2026-04-17 contracts compile. JSDoc forbids new contracts from using them; nothing else does.',
    rationale: 'v2.1 hardening exists because architects took shortcuts under deadline. A typed escape hatch sitting next to the strict type is a future shortcut waiting to be taken. The first new contract that imports `LegacyFlintContract` undoes v2.1 silently.',
    proposedFix: 'Extend flint-contract-linter to reject any import of a `Legacy*` symbol from shared/contract-schema.ts unless the contract\'s meta.date is before 2026-04-17.',
    scope: 'cross-file',
    status: 'open',
  },
  {
    id: 'WARN-4',
    title: 'FLINT_FORCE_AUTOUPDATE env-var bypass is a production foot-gun',
    severity: 'warning',
    evidence: [
      { file: 'electron/autoUpdater.ts', line: 70, excerpt: "if (process.env.FLINT_FORCE_AUTOUPDATE !== '1') {" },
      { file: 'electron/autoUpdater.ts', line: 77, note: 'guard skipped when env var is set — autoUpdater registers handlers + 4h periodic check' },
    ],
    observed: 'The app-update.yml existence guard can be bypassed by setting an environment variable. Comment says "for unit tests."',
    rationale: 'Test-only env vars leak. CI parents, beta-tester shells, and supervisor processes all set environment variables that descend into child processes. If this var ever leaks into a packaged build with no real update feed, the autoUpdater will fire periodic background errors every 4 hours.',
    proposedFix: 'Replace process.env read with an explicit injected option: `initAutoUpdater(win, { forceForTesting?: boolean })`. Tests pass the option directly; production callers cannot.',
    scope: 'one-file',
    status: 'open',
  },
  {
    id: 'WARN-5',
    title: 'tokenMatcher CATEGORY_TO_TOKEN_TYPE fix is a real behavior change without a regression test',
    severity: 'warning',
    evidence: [
      { file: 'src/utils/tokenMatcher.ts', line: 230, excerpt: "spacing: 'dimension', borderRadius: 'dimension'," },
      { file: 'flint-mcp/src/core/governance/types.ts', note: 'engine emits token_type === "dimension" for both spacing and radius per DTCG normalization' },
    ],
    observed: 'Pre-cleanup mapping had spacing→"spacing" and borderRadius→"borderRadius", neither of which is a valid token_type in the engine. Cleanup remapped both to "dimension".',
    rationale: 'This is a real bug fix wearing a TSC-cleanup hat. Pre-fix, the inspector silently flagged every spacing and border-radius value as off-token because the type filter never matched anything. Post-fix, the INSPECTOR.1 contract finally works as designed. The behavior change deserves an explicit regression test.',
    proposedFix: 'Add two assertions to tokenMatcher tests: matchValueToToken("8px","spacing",[dimToken8px]).inTokenSet === true and matchValueToToken("4px","borderRadius",[dimToken4px]).inTokenSet === true.',
    scope: 'one-file',
    status: 'open',
  },
  {
    id: 'SUG-1',
    title: '{ code?: string } structural shadow is fine but loses the NodeJS.ErrnoException intent',
    severity: 'suggestion',
    evidence: [
      { file: 'src/store/canvasStore.ts', line: 833, excerpt: "const code = (err as { code?: string })?.code ?? 'unknown'" },
      { file: 'src/lib/autoResume.ts', line: 168 },
    ],
    observed: 'Two sites replace `NodeJS.ErrnoException` with the structural shape `{ code?: string }` to drop the `@types/node` dependency from src/.',
    rationale: 'Compiles correctly. Loses the semantic signal "this is an fs/syscall error." Future readers will not know whether to expect errno/syscall/path on the value.',
    proposedFix: 'Define `interface NodeErrorLike { code?: string; errno?: number; syscall?: string; path?: string }` in shared/ and import where needed.',
    scope: 'cross-file',
    status: 'open',
  },
  {
    id: 'SUG-2',
    title: 'window double-cast in src/main.tsx lacks an explanatory comment',
    severity: 'suggestion',
    evidence: [
      { file: 'src/main.tsx', note: '(window as unknown as Record<string, unknown>) — canonical TS escape, no comment' },
    ],
    observed: 'The double-cast is correct for attaching test hooks to window. No comment explains why it is required.',
    rationale: 'Unexplained casts attract well-intentioned cleanup PRs that break the bridging.',
    proposedFix: 'Add a one-line comment: `// double-cast: Window is not extensible; attach for e2e harness`.',
    scope: 'one-line',
    status: 'open',
  },
  {
    id: 'SUG-3',
    title: 'Vue/Svelte adapter sideEffects: [] return is a silent stub',
    severity: 'suggestion',
    evidence: [
      { file: 'src/core/adapters/VueAdapter.ts', note: 'applyMutationBatch returns sideEffects: []' },
      { file: 'src/core/adapters/SvelteAdapter.ts', note: 'same' },
    ],
    observed: 'Both adapters now return `sideEffects: []` to satisfy IFlintAdapter.',
    rationale: 'Empty array means "no side effects ever." If these adapters are still skeletons (queued per project_preview_framework_support.md), the empty stub will ship by accident the first time someone wires them in.',
    proposedFix: 'Add `// TODO(framework-agnostic): populate sideEffects when adapter implementation lands` next to each return.',
    scope: 'one-line',
    status: 'open',
  },
];

export const REPORT: ReviewReport = {
  meta: {
    phase: 'TSC-CLEANUP',
    dimension: 'code',
    reviewer: 'flint-code-reviewer',
    date: '2026-04-25',
    round: 1,
    scope: [
      'TSC baseline cleanup (~110 files)',
      'shared/contract-schema.ts Legacy* additions',
      'tsconfig partition (app/node/tests)',
      'src/types/flint-api.d.ts type union additions',
      'src/utils/tokenMatcher.ts CATEGORY_TO_TOKEN_TYPE fix',
      'electron/autoUpdater.ts env-var bypass',
    ],
    markdownFile: 'TSC-CLEANUP-code-review-2026-04-25.md',
  },
  rubric: [
    { criterion: 'tsc -b exits 0', result: 'pass' },
    { criterion: 'No new `as any` casts without explanatory comment', result: 'fail', evidence: 'Three triple-casts in GovernanceDashboard:466-468 are uncommented (WARN-1)', relatedFindings: ['WARN-1'] },
    { criterion: 'Test-config relaxations are scoped + documented', result: 'fail', evidence: 'tsconfig.tests.json relaxes 2 flags with no explanatory comment (WARN-2)', relatedFindings: ['WARN-2'] },
    { criterion: 'Process boundary preserved (no fs/sqlite/Node imports in src/)', result: 'pass' },
    { criterion: 'No regex source-code modification introduced', result: 'pass' },
    { criterion: 'Behavior changes have regression tests', result: 'fail', evidence: 'tokenMatcher mapping change is a real bug fix without a regression test (WARN-5)', relatedFindings: ['WARN-5'] },
    { criterion: 'Test-only escape hatches are not env-var-driven', result: 'fail', evidence: 'autoUpdater.ts:70 uses FLINT_FORCE_AUTOUPDATE env var (WARN-4)', relatedFindings: ['WARN-4'] },
    { criterion: 'Grandfather types are enforced (not just JSDoc-warned)', result: 'fail', evidence: 'Legacy* contract types have no linter enforcement (WARN-3)', relatedFindings: ['WARN-3'] },
    { criterion: 'IPC validator schemas remain present (Zod 4 migration)', result: 'pass', evidence: 'shared/ipc-validators.ts:274 z.record(z.string(), z.unknown()) — correct Zod 4 API' },
    { criterion: 'Stub adapters disclose their stub status', result: 'fail', evidence: 'Vue/Svelte adapter sideEffects: [] is silent (SUG-3)', relatedFindings: ['SUG-3'] },
  ],
  findings,
  counts: countFindings(findings),
  verdict: deriveVerdict(findings, 'code'),
  scopeCoverage: {
    reviewed: [
      'shared/contract-schema.ts',
      'shared/review-schema.ts',
      'shared/ipc-validators.ts',
      'tsconfig.app.json',
      'tsconfig.node.json',
      'tsconfig.tests.json',
      'src/types/flint-api.d.ts',
      'src/utils/tokenMatcher.ts',
      'src/components/ui/FixPreviewDrawer.tsx',
      'src/components/ui/GovernanceDashboard.tsx',
      'src/components/ui/mint/EmitDropdown.tsx',
      'src/store/canvasStore.ts',
      'src/lib/autoResume.ts',
      'src/main.tsx',
      'src/store/__tests__/tokenStore.protoPollution.test.ts',
      'src/core/adapters/VueAdapter.ts',
      'src/core/adapters/SvelteAdapter.ts',
      'electron/autoUpdater.ts',
      'electron/main.ts (spot checks: pt undefined, HydroResolvedDef cast, variantVal guard, Dirent widening, filePath shadow)',
    ],
    skipped: [
      'All test-file behavior changes — already verified passing by user',
      'electron/preload.ts — security-reviewer scope, not code-reviewer scope',
      'server/index.ts web-build parity — not in TSC cleanup scope per user prompt',
      'Bulk perl/sed (window.flintAPI.X as Record<...>) replacements — sampled main.tsx, did not exhaustively re-grep all 110 files. Follow-up grep recommended.',
    ],
  },
};
